# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid_denormalize}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Logan Raarup}]
  s.date = %q{2011-10-24}
  s.description = %q{Helper module for denormalizing association attributes in Mongoid models.}
  s.email = %q{logan@logan.dk}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "lib/mongoid_denormalize.rb",
    "lib/railties/denormalize.rake",
    "lib/railties/railtie.rb"
  ]
  s.homepage = %q{http://github.com/logandk/mongoid_denormalize}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Mongoid denormalization helper.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

